#!/bin/bash

BASEDIR="$(dirname $0)"
SHARE_LIST_FILE="${BASEDIR}/share-list.txt"

function print_usage() {
    echo "--- usage:"
    echo "--- config-share \"action\""
    echo "------ \"action\" in { package, unpackage }"
}

function validate_input() {
    if [ ! "$1" == "package" ] && [ ! "$1" == "unpackage" ]; then
        echo "Invalid input."
        print_usage
        exit 1
    else
        ACTION="$1"
    fi
}

function cycle_through_share_list() {
    while read line

    done < <( cat "${SHARE_LIST_FILE}" | grep -v '#' | grep -v '^$' )
}

function package() {
    echo "Packaging.."

    


}

function unpackage() {
    echo "Unpackaging.."
}

function main() {
    validate_input "${@}"

    case "${ACTION}" in
        "package")
            package
            ;;
        "unpackage")
            unpackage
            ;;
        *)
            echo "This should never be reached."
            ;;
    esac

    echo "Done."
}

main "${@}"